# Project-wide Gradle settings.
# Membatasi memori Gradle ke 3GB dan Kotlin Daemon ke 1GB agar total penggunaan RAM aman (Laptop 7GB)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
kotlin.daemon.jvm.options=-Xmx1024m
kotlin.code.style=official

# AndroidX support
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
